import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY OBSIDIAN
IT SHOULD NOT BE EDITED DIRECTLY
*/

`;

const prod = (process.argv[2] === '--minify');
await esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: ['obsidian'],
	format: 'cjs',
	target: 'node16',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outdir: `.`,
	minify: prod,
	sourcesContent: false,
	define: { 'globalThis': 'globalThis' },
	platform: 'node',
	color: true,
});